; 调整十字光标轴线不同的角度，以配合自动方向定位直接输入距离
(defun c:0 () 
<<<<<<< HEAD
  (setvar "snapang" 0)
  (prin1)
)
(defun c:15 () 
  (setvar "snapang" (* 15 (/ 180 pi)))
  (prin1)
)
(defun c:30 () 
  (setvar "snapang" (* 30 (/ 180 pi)))
  (prin1)
)
(defun c:45 () 
  (setvar "snapang" (* 45 (/ 180 pi)))
  (prin1)
)
(defun c:60 () 
  (setvar "snapang" (* 60 (/ 180 pi)))
  (prin1)
)
(defun c:75 () 
  (setvar "snapang" (* 75 (/ 180 pi)))
=======
  (setvar "sanpang" 0)
  (prin1)
)
(defun c:15 () 
  (setvar "sanpang" (* 15 (/ 180 pi)))
  (prin1)
)
(defun c:30 () 
  (setvar "sanpang" (* 30 (/ 180 pi)))
  (prin1)
)
(defun c:45 () 
  (setvar "sanpang" (* 45 (/ 180 pi)))
  (prin1)
)
(defun c:60 () 
  (setvar "sanpang" (* 60 (/ 180 pi)))
  (prin1)
)
(defun c:75 () 
  (setvar "sanpang" (* 75 (/ 180 pi)))
>>>>>>> 1caf9248b4888830741440197568728bf9e22d7c
  (prin1)
)
(prompt "直接输入0、15、30、45、60、75 十字光标轴线调整值")
(prin1)

